In [10]:
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('data/survey_results_public.csv', index_col= 'Respondent')

In [11]:
df.loc[33,'CompFreq']

'Monthly'

In [12]:
filt = (df['Country'] == 'Germany')

In [13]:
filt2 = (df['Country'] == 'United States') & (df['Hobbyist'] == 'Yes')

In [14]:
len(df.loc[filt])

3890

In [15]:
b = len(df.loc[filt2])

In [16]:
filt3 = df['ConvertedComp'] > 70000

In [17]:
df.loc[filt3]

,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,CurrencySymbol,...,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
Respondent,,,,,,,,,,,,,,,,,,,,,
8,I am a developer by profession,Yes,36.0,12,Yearly,116000.0,116000.0,United States,United States dollar,USD,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",Django;React.js;Vue.js,Flask,Just as welcome now as I felt last year,39.0,17,13
16,I am a developer by profession,Yes,45.0,8,Monthly,7000.0,108576.0,United Kingdom,Pound sterling,GBP,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",NaN,jQuery;React.js,Just as welcome now as I felt last year,50.0,37,23
17,I am a developer by profession,Yes,25.0,14,Yearly,79000.0,79000.0,United States,United States dollar,USD,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",ASP.NET Core;Gatsby;React.js;Vue.js,ASP.NET;Gatsby;jQuery;React.js;Vue.js,Just as welcome now as I felt last year,40.0,7,3
18,I am a developer by profession,Yes,32.0,12,Monthly,105000.0,1260000.0,United States,United States dollar,USD,...,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",NaN,NaN,Just as welcome now as I felt last year,45.0,19,12
19,I am a developer by profession,No,24.0,15,Yearly,83400.0,83400.0,United States,United States dollar,USD,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",Django;Express;React.js,Angular;Angular.js;ASP.NET Core,Just as welcome now as I felt last year,35.0,9,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65586,I am a developer by profession,Yes,NaN,8,Yearly,225000.0,225000.0,United States,United States dollar,USD,...,NaN,NaN,NaN,Mathematics or statistics,NaN,NaN,NaN,50.0,25,15
65589,I am a developer by profession,Yes,NaN,16,Yearly,150000.0,150000.0,United States,United States dollar,USD,...,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,NaN,45.0,10,6
65602,"I am not primarily a developer, but I write co...",Yes,NaN,13,Yearly,140000.0,140000.0,United States,United States dollar,USD,...,NaN,NaN,NaN,"Another engineering discipline (such as civil,...",NaN,NaN,NaN,NaN,15,12
65604,I am a developer by profession,No,NaN,13,Weekly,3000.0,150000.0,United States,United States dollar,USD,...,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,NaN,45.0,7,4
65617,I am a developer by profession,Yes,NaN,15,Yearly,120000.0,129718.0,Germany,European Euro,EUR,...,NaN,NaN,NaN,"Another engineering discipline (such as civil,...",NaN,NaN,Just as welcome now as I felt last year,35.0,9,9

In [18]:
contries = ['United States', 'Germany', 'India', 'United Kingdom', 'Canada']
filter3 = df['Country'].isin(contries)

In [19]:
df.loc[-filter3, 'Country']

Respondent
3        Russian Federation
4                   Albania
9                   Tunisia
12                    Spain
13              Netherlands
                ...
64567           Netherlands
64867               Morocco
64898              Viet Nam
64925                Poland
65112                 Spain
Name: Country, Length: 33612, dtype: object

In [20]:
filter4 = df['LanguageWorkedWith'].str.contains('Python', na = False)

In [21]:
df.loc[filter4, 'LanguageWorkedWith']

Respondent
3                                 Objective-C;Python;Swift
8                                               Python;SQL
10                     HTML/CSS;Java;JavaScript;Python;SQL
13                                     C;JavaScript;Python
15        Bash/Shell/PowerShell;C;HTML/CSS;Java;Python;SQL
                               ...
61561    Bash/Shell/PowerShell;HTML/CSS;JavaScript;Perl...
62391       C++;HTML/CSS;JavaScript;Python;Ruby;TypeScript
63077              C++;HTML/CSS;Java;JavaScript;Python;SQL
63640    Bash/Shell/PowerShell;C;C#;C++;HTML/CSS;Java;J...
64867    Assembly;Bash/Shell/PowerShell;C;C#;C++;Dart;G...
Name: LanguageWorkedWith, Length: 25287, dtype: object

In [22]:
#df.columns = range(1,61,1)

In [23]:
filter5 = df['Country'].isin(['United States', 'Germany', 'India', 'United Kingdom', 'Canada'])

In [24]:
df.loc[-filter5, 'Country']

Respondent
3        Russian Federation
4                   Albania
9                   Tunisia
12                    Spain
13              Netherlands
                ...
64567           Netherlands
64867               Morocco
64898              Viet Nam
64925                Poland
65112                 Spain
Name: Country, Length: 33612, dtype: object

In [25]:
filter6 = df['LanguageWorkedWith'].str.contains('Python', na=False)

In [26]:
df.loc[filter6,'LanguageWorkedWith']

Respondent
3                                 Objective-C;Python;Swift
8                                               Python;SQL
10                     HTML/CSS;Java;JavaScript;Python;SQL
13                                     C;JavaScript;Python
15        Bash/Shell/PowerShell;C;HTML/CSS;Java;Python;SQL
                               ...
61561    Bash/Shell/PowerShell;HTML/CSS;JavaScript;Perl...
62391       C++;HTML/CSS;JavaScript;Python;Ruby;TypeScript
63077              C++;HTML/CSS;Java;JavaScript;Python;SQL
63640    Bash/Shell/PowerShell;C;C#;C++;HTML/CSS;Java;J...
64867    Assembly;Bash/Shell/PowerShell;C;C#;C++;Dart;G...
Name: LanguageWorkedWith, Length: 25287, dtype: object